[PHP]
display_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
extension_dir = "C:\Users\nagar\Music\Matrimonial web portal + admin panel\dada project\php74\ext"
extension=curl
extension=fileinfo
extension=php_gd2
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=sockets
extension=soap
extension=xsl
extension=exif
extension=ldap
zend_extension=opcache
extension=sodium
extension=tidy
date.timezone = UTC
memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
