[PHP]
display_errors = On
error_reporting = E_ALL
extension_dir = ext
extension=curl
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=sockets
extension=soap
extension=xsl
extension=bz2
extension=exif
extension=gmp
extension=imap
extension=ldap
extension=odbc
extension=opcache
extension=sodium
extension=tidy
extension=sockets
extension=ffi
extension=gettext
extension=ftp
extension=shmop
extension=snmp
extension=soap
extension=sodium
CLI = php.exe
date.timezone = UTC
memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
